# -*- coding: utf-8 -*-
"""coversion.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DulE03ectsIuaTJp_pEUnbbLDp1bGLzu
"""

# Distance conversion
kilometer = 15

print (kilometer, "km = ", kilometer * 0.62, "m")

# Temperature conversion
celsius = 22

print (celsius, "degree = ", (celsius * 9/5) + 32, "F")

# Binary conversion
binary = 101101000

print (binary, " = ", int(str(binary),2))